# Linking School Quality to Road Conditions: A Comprehensive Analysis and Prediction of Pavement Quality Using NYC Education Data

### Importing and Linking Data

In [ ]:
# Import Datasets
import pandas as pd
pavement = pd.read_csv('pavement.csv')
locations = pd.read_csv('SchoolLocations.csv')

In [2]:
# Import School Data Info (2023)
student = pd.read_excel('2023student.xlsx')
family = pd.read_excel('2023familiies.xlsx')
teacher = pd.read_excel('2023teacher.xlsx')

In [3]:
# Combine 2023
twentythree = pd.concat([student, family, teacher], ignore_index=True)
print(twentythree.head())

      DBN                     School Name  Total Parent Response Count  \
0     NaN                             NaN                          NaN
1  01M015       P.S. 015 Roberto Clemente                         65.0
2  01M020            P.S. 020 Anna Silver                         98.0
3  01M034  P.S. 034 Franklin D. Roosevelt                         50.0
4  01M063       The STAR Academy - P.S.63                         65.0

   Total Parent Response Rate  Total Student Response Rate  \
0                         NaN                          NaN
1                         NaN                          NaN
2                         NaN                          NaN
3                         NaN                         0.81
4                         NaN                          NaN

   Total Teacher Response Rate  Collaborative Teachers Score  \
0                          NaN                           NaN
1                         1.00                           NaN
2                         0.76                           NaN
3                         0.80                           NaN
4                         0.95                           NaN

   Effective School Leadership Score  Rigorous Instruction Score  \
0                                NaN                         NaN
1                                NaN                         NaN
2                                NaN                         NaN
3                                NaN                         NaN
4                                NaN                         NaN

   Supportive Environment Score  Strong Family-Community Ties Score  \
0                           NaN                                 NaN
1                           NaN                                 NaN
2                           NaN                                 NaN
3                           NaN                                 NaN
4                           NaN                                 NaN

   Trust Score  Total Family Response Count  Total Family Response Rate
0          NaN                          NaN                         NaN
1          NaN                          NaN                         NaN
2          NaN                          NaN                         NaN
3          NaN                          NaN                         NaN
4          NaN                          NaN                         NaN

In [8]:
# Import School Data Info (2022)
student = pd.read_excel('2022student.xlsx')
family = pd.read_excel('2022family.xlsx')
teacher = pd.read_excel('2022teacher.xlsx')

In [11]:
# Combine 2022
twentytwo = pd.concat([student, family, teacher], ignore_index=True)
print(twentytwo.head())

  Unnamed Column                Unnamed Column 1  Unnamed Column 2  \
0         01M034  P.S. 034 Franklin D. Roosevelt              75.0
1         01M140          P.S. 140 Nathan Straus              51.0
2         01M184            P.S. 184m Shuang Wen              87.0
3         01M188      P.S. 188 The Island School              70.0
4         01M292      Orchard Collegiate Academy              35.0

   q1. Most students at this school treat each other with respect.\n\nStrongly Disagree/Disagree  \
0                                               37.0
1                                               14.0
2                                               11.0
3                                                1.0
4                                                1.0

   q1. Most students at this school treat each other with respect.\n\nStrongly Agree/Agree  \
0                                               63.0
1                                               86.0
2                                               89.0
3                                               99.0
4                                               99.0

   q2. At this school, students with disabilities are included in all school activities.Strongly Disagree/Disagree  \
0                                               18.0
1                                                3.0
2                                               13.0
3                                                1.0
4                                                0.0

   q2. At this school, students with disabilities are included in all school activities.Strongly Agree/Agree  \
0                                               82.0
1                                               97.0
2                                               87.0
3                                               99.0
4                                              100.0

   q3. My school encourages and includes student input in decision-making processes.Strongly Disagree/Disagree  \
0                                               10.0
1                                                4.0
2                                                9.0
3                                                1.0
4                                                5.0

   q3. My school encourages and includes student input in decision-making processes.Strongly Agree/Agree  \
0                                               90.0
1                                               96.0
2                                               91.0
3                                               99.0
4                                               95.0

   q4. My teachers use examples of students' different cultures/backgrounds/families in their lessons to make learning more meaningful for me.Strongly Disagree/Disagree  \
0                                               11.0
1                                               12.0
2                                               22.0
3                                                1.0
4                                                6.0

   ...  \
0  ...
1  ...
2  ...
3  ...
4  ...

   q172. Adults at this school...create an atmosphere that encourages students to continue their education after high school.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q172. Adults at this school...create an atmosphere that encourages students to continue their education after high school.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q173. Adults at this school...provide students with information about the college application process.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q173. Adults at this school...provide students with information about the college application process.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q174. Adults at this school...help students consider which colleges to apply to.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q174. Adults at this school...help students consider which colleges to apply to.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q175. Adults at this school...help students plan for how to meet their future career goals.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q175. Adults at this school...help students plan for how to meet their future career goals.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q176. Adults at this school...show students options for how to pay for college (scholarship, grants, loans, work study programs).\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q176. Adults at this school...show students options for how to pay for college (scholarship, grants, loans, work study programs).\n\nStrongly disagree/Disagree
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

[5 rows x 571 columns]

In [15]:
# Import School Data (2021)
student = pd.read_csv('2021student.csv')
family = pd.read_csv('2021family.csv')
teacher = pd.read_csv('2021teacher.csv')

In [16]:
# Combine 2021
twentyone = pd.concat([student, family, teacher], ignore_index=True)
print(twentyone.head())

  Unnamed Column                Unnamed Column 1  Unnamed Column 2  \
0         01M034  P.S. 034 Franklin D. Roosevelt              75.0
1         01M140          P.S. 140 Nathan Straus              51.0
2         01M184            P.S. 184m Shuang Wen              87.0
3         01M188      P.S. 188 The Island School              70.0
4         01M292      Orchard Collegiate Academy              35.0

   q1. Most students at this school treat each other with respect.\n\nStrongly Disagree/Disagree  \
0                                               37.0
1                                               14.0
2                                               11.0
3                                                1.0
4                                                1.0

   q1. Most students at this school treat each other with respect.\n\nStrongly Agree/Agree  \
0                                               63.0
1                                               86.0
2                                               89.0
3                                               99.0
4                                               99.0

   q2. At this school, students with disabilities are included in all school activities.Strongly Disagree/Disagree  \
0                                               18.0
1                                                3.0
2                                               13.0
3                                                1.0
4                                                0.0

   q2. At this school, students with disabilities are included in all school activities.Strongly Agree/Agree  \
0                                               82.0
1                                               97.0
2                                               87.0
3                                               99.0
4                                              100.0

   q3. My school encourages and includes student input in decision-making processes.Strongly Disagree/Disagree  \
0                                               10.0
1                                                4.0
2                                                9.0
3                                                1.0
4                                                5.0

   q3. My school encourages and includes student input in decision-making processes.Strongly Agree/Agree  \
0                                               90.0
1                                               96.0
2                                               91.0
3                                               99.0
4                                               95.0

   q4. My teachers use examples of students' different cultures/backgrounds/families in their lessons to make learning more meaningful for me.Strongly Disagree/Disagree  \
0                                               11.0
1                                               12.0
2                                               22.0
3                                                1.0
4                                                6.0

   ...  \
0  ...
1  ...
2  ...
3  ...
4  ...

   q172. Adults at this school...create an atmosphere that encourages students to continue their education after high school.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q172. Adults at this school...create an atmosphere that encourages students to continue their education after high school.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q173. Adults at this school...provide students with information about the college application process.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q173. Adults at this school...provide students with information about the college application process.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q174. Adults at this school...help students consider which colleges to apply to.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q174. Adults at this school...help students consider which colleges to apply to.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q175. Adults at this school...help students plan for how to meet their future career goals.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q175. Adults at this school...help students plan for how to meet their future career goals.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q176. Adults at this school...show students options for how to pay for college (scholarship, grants, loans, work study programs).\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q176. Adults at this school...show students options for how to pay for college (scholarship, grants, loans, work study programs).\n\nStrongly disagree/Disagree
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

[5 rows x 571 columns]

In [17]:
# Import School Data (2019)
student = pd.read_excel('2019student.xlsx')
family = pd.read_excel('2019family.xlsx')
teacher = pd.read_excel('2019teacher.xlsx')

In [18]:
# Combine 2019
nineteen = pd.concat([student, family, teacher], ignore_index=True)
print(nineteen.head())

      DBN                School Name  Total Parent \nResponse Rate  \
0     NaN                        NaN                           NaN
1     NaN                        NaN                           NaN
2  01M015  P.S. 015 ROBERTO CLEMENTE                          91.0
3  01M019        P.S. 019 ASHER LEVY                         100.0
4  01M020       P.S. 020 ANNA SILVER                          58.0

   Total Teacher Response Rate  Total Student Response Rate  \
0                          NaN                          NaN
1                          NaN                          NaN
2                        100.0                          NaN
3                         93.0                          NaN
4                         90.0                          NaN

   Collaborative Teachers Score  Effective School Leadership Score  \
0                           NaN                                NaN
1                           NaN                                NaN
2                          4.10                               4.19
3                          4.53                               4.51
4                          2.71                               2.98

   Rigorous Instruction Score  Supportive Environment Score  \
0                         NaN                           NaN
1                         NaN                           NaN
2                        4.02                           NaN
3                        4.80                           NaN
4                        1.92                           NaN

   Strong Family-Community Ties Score  Trust Score
0                                 NaN          NaN
1                                 NaN          NaN
2                                4.18         3.96
3                                4.66         3.76
4                                3.84         3.14

In [19]:
# Import School Data (2018)
student = pd.read_excel('2018student.xlsx')
family = pd.read_excel('2018family.xlsx')
teacher = pd.read_excel('2018teacher.xlsx')

In [20]:
# Combine 2018
eighteen = pd.concat([student, family, teacher], ignore_index=True)
print(eighteen.head())

      DBN                     School Name  Total Parent \nResponse Rate  \
0     NaN                             NaN                           NaN
1  01M015       P.S. 015 ROBERTO CLEMENTE                          75.0
2  01M019             P.S. 019 ASHER LEVY                          96.0
3  01M020            P.S. 020 ANNA SILVER                          50.0
4  01M034  P.S. 034 FRANKLIN D. ROOSEVELT                          29.0

   Total Teacher Response Rate  Total Student Response Rate  \
0                          NaN                          NaN
1                        100.0                          NaN
2                         95.0                          NaN
3                         89.0                          NaN
4                         78.0                         92.0

   Collaborative Teachers Score  Effective School Leadership Score  \
0                           NaN                                NaN
1                          4.12                               4.09
2                          4.27                               4.25
3                          2.76                               3.04
4                          2.40                               2.45

   Rigorous Instruction Score  Supportive Environment Score  \
0                         NaN                           NaN
1                        3.91                           NaN
2                        4.64                           NaN
3                        1.94                           NaN
4                        2.04                           NaN

   Strong Family-Community Ties Score  Trust Score
0                                 NaN          NaN
1                                3.80         3.99
2                                4.10         3.55
3                                3.64         3.12
4                                3.33         2.32

In [21]:
# Import School Data (2017)
student = pd.read_excel('2017student.xlsx')
family = pd.read_excel('2017family.xlsx')
teacher = pd.read_excel('2017teacher.xlsx')

In [22]:
# Combine 2017
seventeen = pd.concat([student, family, teacher], ignore_index=True)
print(seventeen.head())

      DBN                School Name  Total Parent \nResponse Rate  \
0     NaN                        NaN                           NaN
1     NaN                        NaN                           NaN
2  01M015  P.S. 015 Roberto Clemente                          88.0
3  01M019        P.S. 019 Asher Levy                         100.0
4  01M020       P.S. 020 Anna Silver                          60.0

   Total Teacher Response Rate  Total Student Response Rate  \
0                          NaN                          NaN
1                          NaN                          NaN
2                        100.0                          NaN
3                        100.0                          NaN
4                         91.0                          NaN

   Collaborative Teachers Score  Effective School Leadership Score  \
0                           NaN                                NaN
1                           NaN                                NaN
2                           NaN                                NaN
3                          4.45                               4.55
4                          2.50                               3.01

   Rigorous Instruction Score  Supportive Environment Score  \
0                         NaN                           NaN
1                         NaN                           NaN
2                         NaN                          4.25
3                        4.81                          3.53
4                        1.81                          2.30

   Strong Family-Community Ties Score  Trust Score
0                                 NaN          NaN
1                                 NaN          NaN
2                                 NaN         4.33
3                                3.62         3.73
4                                2.97         2.68

In [23]:
# Combine All Datasets for School Survey
schoolsurvey = pd.concat([seventeen, eighteen, nineteen, twentyone, twentytwo, twentythree], ignore_index=True)
print(schoolsurvey.head())

      DBN                School Name  Total Parent \nResponse Rate  \
0     NaN                        NaN                           NaN
1     NaN                        NaN                           NaN
2  01M015  P.S. 015 Roberto Clemente                          88.0
3  01M019        P.S. 019 Asher Levy                         100.0
4  01M020       P.S. 020 Anna Silver                          60.0

   Total Teacher Response Rate  Total Student Response Rate  \
0                          NaN                          NaN
1                          NaN                          NaN
2                        100.0                          NaN
3                        100.0                          NaN
4                         91.0                          NaN

   Collaborative Teachers Score  Effective School Leadership Score  \
0                           NaN                                NaN
1                           NaN                                NaN
2                           NaN                                NaN
3                          4.45                               4.55
4                          2.50                               3.01

   Rigorous Instruction Score  Supportive Environment Score  \
0                         NaN                           NaN
1                         NaN                           NaN
2                         NaN                          4.25
3                        4.81                          3.53
4                        1.81                          2.30

   Strong Family-Community Ties Score  ...  \
0                                 NaN  ...
1                                 NaN  ...
2                                 NaN  ...
3                                3.62  ...
4                                2.97  ...

   q173. Adults at this school...provide students with information about the college application process.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  q174. Adults at this school...help students consider which colleges to apply to.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  q174. Adults at this school...help students consider which colleges to apply to.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q175. Adults at this school...help students plan for how to meet their future career goals.\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q175. Adults at this school...help students plan for how to meet their future career goals.\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q176. Adults at this school...show students options for how to pay for college (scholarship, grants, loans, work study programs).\n\nAgree/Strongly agree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   q176. Adults at this school...show students options for how to pay for college (scholarship, grants, loans, work study programs).\n\nStrongly disagree/Disagree  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Total Parent Response Count  Total Family Response Count  \
0                          NaN                          NaN
1                          NaN                          NaN
2                          NaN                          NaN
3                          NaN                          NaN
4                          NaN                          NaN

   Total Family Response Rate
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN

[5 rows x 582 columns]

In [26]:
print(pavement.dtypes)

the_geom       object
SegmentID       int64
Length          int64
Width         float64
UsageClass     object
Hagstrom        int64
Bus             int64
Truck           int64
Rating_B        int64
RatingWord     object
RatingDate     object
RatingFY_S      int64
Shape_Leng    float64
dtype: object

In [27]:
print(locations.dtypes)

fiscal_year                            int64
system_code                           object
location_code                         object
location_name                         object
BEDS                                   int64
Managed_by_name                       object
location_type_description             object
Location_Category_Description         object
Grades_text                           object
Grades_final_text                     object
open_date                             object
Status_descriptions                   object
Primary_building_code                 object
primary_address_line_1                object
State_code                            object
X_COORDINATE                         float64
Y_COORDINATE                         float64
LONGITUDE                            float64
LATITUDE                             float64
Community_district                   float64
Council-district                     float64
Census_tract                         float64
Borough_block_lot                    float64
NTA                                   object
NTA_Name                              object
Principal_Name                        object
Principal_title                       object
Principal_phone_number                object
fax_number                            object
Geographical_District_code             int64
Administrative_District_Code           int64
Administrative_District_Name          object
community_school_sup_name             object
Tier_3_Support_Location_Name          object
Tier_3_Support_Leader_Name            object
Tier_2_Support_Location_Name          object
HighSchool_Network_Location_Code      object
HighSchool_Network_Name               object
HighSchool_Network_Superintendent     object
Community_district 1                 float64
Police_precinct                      float64
dtype: object

In [40]:
pavement = pd.DataFrame(pavement)
print(pavement)

                                                the_geom SegmentID  Length  \
0      MULTILINESTRING ((-74.21214990871114 40.516450...       969     589
1      MULTILINESTRING ((-74.20972278371778 40.518920...       983     258
2      MULTILINESTRING ((-74.20649118797381 40.514855...       999     232
3      MULTILINESTRING ((-74.20882121922708 40.519306...      1018      75
4      MULTILINESTRING ((-74.20583882952431 40.517906...      1050     891
...                                                  ...       ...     ...
81204  MULTILINESTRING ((-73.74677984700138 40.747471...    101457     676
81205  MULTILINESTRING ((-73.74751669571391 40.751120...    101473     318
81206  MULTILINESTRING ((-73.74560643488219 40.766498...    101530     284
81207  MULTILINESTRING ((-73.74250347422124 40.758589...    101607     500
81208  MULTILINESTRING ((-73.74126654241009 40.768508...    101666     311

       Width UsageClass  Hagstrom  Bus  Truck  Rating_B RatingWord  \
0      33.08          L         0    0      0         5       FAIR
1      30.00        NaN         0    0      0         9       GOOD
2      30.00        NaN         0    0      0         3       POOR
3      34.58          L         0    0      0         8       GOOD
4      30.00        NaN         0    0      0         5       FAIR
...      ...        ...       ...  ...    ...       ...        ...
81204  30.00          S         0    1      0         8       GOOD
81205  30.00        NaN         0    0      0         8       GOOD
81206  44.17          L         0    0      0         3       POOR
81207  15.33          L         0    0      0         7       GOOD
81208  34.75          L         0    0      0         8       GOOD

                   RatingDate  RatingFY_S  Shape_Leng Longitude Latitude
0      01/24/2020 12:00:00 AM        2020  609.854259      None     None
1      05/20/2021 12:00:00 AM        2020  257.932162      None     None
2      10/01/2019 12:00:00 AM        2020  379.637985      None     None
3      10/01/2019 12:00:00 AM        2020   50.289164      None     None
4      01/13/2020 12:00:00 AM        2020  786.400025      None     None
...                       ...         ...         ...       ...      ...
81204  06/07/2021 12:00:00 AM        2021  681.535032      None     None
81205  08/29/2020 12:00:00 AM        2021  332.987988      None     None
81206  06/08/2021 12:00:00 AM        2021  289.527201      None     None
81207  12/26/2019 12:00:00 AM        2020  510.327346      None     None
81208  01/19/2021 12:00:00 AM        2021  329.188396      None     None

[81209 rows x 15 columns]

In [46]:
locations = pd.DataFrame(locations)
print(locations)

      fiscal_year system_code location_code  \
0            2020      15K001          K001
1            2020      17K002          K002
2            2020      13K003          K003
3            2020      75K004          K004
4            2020      16K005          K005
...           ...         ...           ...
2185         2020      84X729          X729
2186         2020      84X730          X730
2187         2020      75X754          X754
2188         2020      75X811          X811
2189         2020      75X811          X811

                                location_name          BEDS Managed_by_name  \
0                         P.S. 001 The Bergen  331500010001             DOE
1                Parkside Preparatory Academy  331700010002             DOE
2                P.S. 003 The Bedford Village  331300010003             DOE
3                                   P.S. K004  307500013004             DOE
4                  P.S. 005 Dr. Ronald McNair  331600010005             DOE
...                                       ...           ...             ...
2185             Readnet Bronx Charter School  320700860842         Charter
2186        Bronx Charter School for the Arts  320800860846         Charter
2187  J. M. Rapport School Career Development  307500012754             DOE
2188                                P.S. X811  307500012811             DOE
2189                                P.S. X811  307500012811             DOE

     location_type_description    Location_Category_Description  \
0             General Academic                       Elementary
1             General Academic  Junior High-Intermediate-Middle
2             General Academic                       Elementary
3            Special Education                       Elementary
4             General Academic                       Elementary
...                        ...                              ...
2185          General Academic                       Elementary
2186          General Academic                       Elementary
2187         Special Education                      High school
2188         Special Education                 Secondary School
2189         Special Education                 Secondary School

                  Grades_text              Grades_final_text  ...  \
0     PK,0K,01,02,03,04,05,SE           PK,0K,01,02,03,04,05  ...
1                 06,07,08,SE                       06,07,08  ...
2     PK,0K,01,02,03,04,05,SE           PK,0K,01,02,03,04,05  ...
3     PK,0K,01,02,03,04,05,SE  PK,0K,01,02,03,04,05,06,07,SE  ...
4     PK,0K,01,02,03,04,05,SE           PK,0K,01,02,03,04,05  ...
...                       ...                            ...  ...
2185                    01,02                            NaN  ...
2186  0K,01,02,03,04,05,06,07     0K,01,02,03,04,05,06,07,08  ...
2187           09,10,11,12,SE                 09,10,11,12,SE  ...
2188        08,09,10,11,12,SE           07,08,09,10,11,12,SE  ...
2189        08,09,10,11,12,SE           07,08,09,10,11,12,SE  ...

      Administrative_District_Name community_school_sup_name  \
0     COMMUNITY SCHOOL DISTRICT 15               SKOP, ANITA
1     COMMUNITY SCHOOL DISTRICT 17           ELLIS, CLARENCE
2     COMMUNITY SCHOOL DISTRICT 13            SAMUELS, KAMAR
3       CITYWIDE SPECIAL EDUCATION        LOUISSAINT, KETLER
4     COMMUNITY SCHOOL DISTRICT 16           MARTIN, YOLANDA
...                            ...                       ...
2185     OFFICE OF CHARTER SCHOOLS                       NaN
2186     OFFICE OF CHARTER SCHOOLS                       NaN
2187    CITYWIDE SPECIAL EDUCATION        LOUISSAINT, KETLER
2188    CITYWIDE SPECIAL EDUCATION        LOUISSAINT, KETLER
2189    CITYWIDE SPECIAL EDUCATION        LOUISSAINT, KETLER

                Tier_3_Support_Location_Name Tier_3_Support_Leader_Name  \
0     NYCDOE Borough Office - Brooklyn North                        NaN
1     NYCDOE Borough Office - Brooklyn South        Mauriciere de Govia
2     NYCDOE Borough Office - Brooklyn North                        NaN
3                           D75 CITYWIDE BCO            Tillman Roberto
4     NYCDOE Borough Office - Brooklyn North                        NaN
...                                      ...                        ...
2185                                     NaN                        NaN
2186                                     NaN                        NaN
2187                        D75 CITYWIDE BCO            Tillman Roberto
2188                        D75 CITYWIDE BCO            Tillman Roberto
2189                        D75 CITYWIDE BCO            Tillman Roberto

               Tier_2_Support_Location_Name  HighSchool_Network_Location_Code  \
0     School Support Team 5- Brooklyn North                               NaN
1     School Support Team 2- Brooklyn South                               NaN
2     School Support Team 3- Brooklyn North                               NaN
3                Children First Network 752                               NaN
4     School Support Team 4- Brooklyn North                               NaN
...                                     ...                               ...
2185                                    NaN                               NaN
2186                                    NaN                               NaN
2187             Children First Network 755                               NaN
2188             Children First Network 755                               NaN
2189             Children First Network 755                               NaN

      HighSchool_Network_Name  HighSchool_Network_Superintendent  \
0                         NaN                                NaN
1                         NaN                                NaN
2                         NaN                                NaN
3                         NaN                                NaN
4                         NaN                                NaN
...                       ...                                ...
2185                      NaN                                NaN
2186                      NaN                                NaN
2187                      NaN                                NaN
2188                      NaN                                NaN
2189                      NaN                                NaN

      Community_district 1  Police_precinct
0                    307.0             72.0
1                    309.0             71.0
2                    303.0             79.0
3                    305.0             75.0
4                    303.0             81.0
...                    ...              ...
2185                 201.0             40.0
2186                 202.0             41.0
2187                 201.0             40.0
2188                 203.0             42.0
2189                 203.0             42.0

[2190 rows x 41 columns]

In [ ]:
def extract_coordinates(geom):
    # Use regex to find all coordinate pairs
    coords = re.findall(r'\((-?\d+\.\d+) (-?\d+\.\d+)', geom)
    # Flatten the list of tuples and convert to float
    coords_flat = [float(coord) for pair in coords for coord in pair]
    return coords_flat

# Apply the function to extract coordinates
extracted_coords = df['the_geom'].apply(extract_coordinates)

# Create a DataFrame from the extracted coordinates
coords_df = pd.DataFrame(extracted_coords.tolist())

# Fill missing values with NaN
coords_df = coords_df.apply(lambda x: x.astype(float) if x.notnull().any() else np.nan)

# Determine the number of coordinate pairs for renaming
num_pairs = coords_df.shape[1] // 2  # Each pair has a longitude and latitude

# Generate new column names
new_col_names = [f'longitude{i+1}' for i in range(num_pairs)] + [f'latitude{i+1}' for i in range(num_pairs)]

# Concatenate the new columns to the original DataFrame
df = pd.concat([df, coords_df], axis=1)

# Rename columns based on the new column names
df.columns = ['the_geom'] + new_col_names

# Display the DataFrame with new coordinate columns
print(df)